#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

# This script contains additional CI checks to run for this specific package

set -e

echo "### Checking for duplicate dependency versions in the normal dependency graph with all features enabled"
cargo tree -d --edges normal --all-features

# checks whether the features are properly feature-gated
res=$(cargo tree -e no-dev | grep serde) 
if [ "$res" != "" ]; then
    exit 1
fi