[package]
name = "aws-smithy-eventstream"
version = "0.0.0-smithy-rs-head"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "John DiSanti <jdisanti@amazon.com>"]
description = "Event stream logic for smithy-rs."
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/smithy-rs"

[features]
derive-arbitrary = ["arbitrary", "derive_arbitrary"]

[dependencies]
derive_arbitrary = { version = "=1.1.6", optional = true } # 1.2.0 requires Rust 1.63 to compile
arbitrary = { version = "=1.1.3", optional = true } # 1.1.4 requires Rust 1.63 to compile
aws-smithy-types = { path = "../aws-smithy-types" }
bytes = "1"
crc32fast = "1.3"

[dev-dependencies]
bytes-utils = "0.1"

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]
rustdoc-args = ["--cfg", "docsrs"]
# End of docs.rs metadata
