# These are the allowed external types in the `aws-sdk-*` generated crates, checked by CI.
allowed_external_types = [
    "aws_smithy_types::*",
    "aws_credential_types::*",
    "aws_types::*",
    "aws_smithy_runtime_api::*",
    "aws_smithy_async::rt::sleep::*",
    "aws_smithy_async::time::*",
    "aws_smithy_async::future::pagination_stream::PaginationStream",
    # only allowed in from impl for presigned request
    "http::request::Request",

    # TODO(https://github.com/awslabs/smithy-rs/issues/1193): Once tooling permits it, only allow the following types in the `event-stream` feature
    "aws_smithy_eventstream::*",

    # Consider moving making this crate 1.0
    "aws_smithy_runtime::client::identity::cache::IdentityCache",

    ### All below this line need to be fixed:
    # The following are not OK
    "aws_http::request_id::RequestId", # move to aws-types
    # `set_invocation_id_generator` — consider make pub(crate) or moving trait to AwsTypes
    "aws_runtime::invocation_id::SharedInvocationIdGenerator",
    "aws_runtime::invocation_id::InvocationIdGenerator",

    # Pending fix in open PRs:
    "aws_smithy_http::result::*",

    # Pending future fix
    "aws_smithy_http::event_stream::*",
]
