[package]
name = "sdk-versioner"
version = "0.1.0"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>"]
edition = "2021"
license = "Apache-2.0"
publish = false

[workspace]

[profile.release]
# prefer fast compile time over runtime performance
opt-level = 0

[dependencies]
anyhow = "1.0"
clap = { version = "~3.1.18", features = ["derive"] }
toml = { version = "0.5.8", features = ["preserve_order"] }
smithy-rs-tool-common = { version = "0.1", path = "../smithy-rs-tool-common" }

[dev-dependencies]
pretty_assertions = "1"
tempfile = "3"
