[package]
name = "previous-release-comparison"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = { path = "../../build/aws-sdk/sdk/aws-config" }
aws-credential-types = { path = "../../build/aws-sdk/sdk/aws-credential-types", features = ["test-util"] }
aws-sdk-s3 = { path = "../../build/aws-sdk/sdk/s3" }
aws-smithy-runtime = { path = "../../build/aws-sdk/sdk/aws-smithy-runtime", features = ["test-util"] }
criterion = { version = "0.5", features = ["async_tokio"] }
http = "0.2.3"
previous-s3 = { version = "1", package = "aws-sdk-s3", features = ["test-util"] }
previous-runtime = { version = "1", package = "aws-smithy-runtime", features = ["test-util"] }
tokio = { version = "1.23.1", features = ["macros", "test-util", "rt-multi-thread"] }

[profile.release]
debug = 1

[[bench]]
name = "previous_release_comparison"
harness = false
