[package]
name = "inlineable"
version = "0.0.0-smithy-rs-head"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "Russell Cohen <rcoh@amazon.com>"]
edition = "2021"
description = """
The modules of this crate are intended to be inlined directly into the SDK as needed. The dependencies here
are to allow this crate to be compilable and testable in isolation, no client code actually takes these dependencies.
"""
license = "Apache-2.0"
publish = false
repository = "https://github.com/awslabs/smithy-rs"

[features]
# this allows the tests to be excluded from downstream crates to keep dependencies / test times reasonable (e.g. no proptests)
gated-tests = []
default = ["gated-tests"]


[dependencies]
async-trait = "0.1"
aws-smithy-http = { path = "../aws-smithy-http" }
aws-smithy-http-server = { path = "../aws-smithy-http-server" }
aws-smithy-json = { path = "../aws-smithy-json" }
aws-smithy-runtime-api = { path = "../aws-smithy-runtime-api", features = ["client"] }
aws-smithy-types = { path = "../aws-smithy-types" }
aws-smithy-xml = { path = "../aws-smithy-xml" }
bytes = "1"
fastrand = "2.0.0"
futures-util = "0.3"
http = "0.2.1"
md-5 = "0.10.0"
once_cell = "1.16.0"
percent-encoding = "2.2.0"
pin-project-lite = "0.2"
regex = "1.5.5"
tower = { version = "0.4.11", default-features = false }
url = "2.2.2"

[dev-dependencies]
proptest = "1"

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]
rustdoc-args = ["--cfg", "docsrs"]
# End of docs.rs metadata
