[package]
name = "aws-credential-types"
version = "0.0.0-smithy-rs-head"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>"]
description = "Types for AWS SDK credentials."
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/smithy-rs"

[features]
hardcoded-credentials = []
test-util = []

[dependencies]
aws-smithy-async = { path = "../../../rust-runtime/aws-smithy-async" }
aws-smithy-types = { path = "../../../rust-runtime/aws-smithy-types" }
tokio = { version = "1.8.4", features = ["sync"] }
tracing = "0.1"
zeroize = "1"

[dev-dependencies]
aws-smithy-async = { path = "../../../rust-runtime/aws-smithy-async", features = ["rt-tokio"] }

# used to test compatibility
async-trait = "0.1.51"
env_logger = "0.9.0"

tokio = { version = "1.8.4", features = ["full", "test-util", "rt"] }
tracing-test = "0.2.1"

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]
rustdoc-args = ["--cfg", "docsrs"]
# End of docs.rs metadata
