[package]
name = "aws-smithy-http-tower"
version = "0.0.0-smithy-rs-head"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "Russell Cohen <rcoh@amazon.com>"]
description = "Tower-compatible shims for smithy-rs middleware."
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/smithy-rs"

[dependencies]
aws-smithy-types = { path = "../aws-smithy-types" }
aws-smithy-http = { path = "../aws-smithy-http" }
tower = { version = "0.4.4" }
pin-project-lite = "0.2.9"
http = "0.2.3"
bytes = "1"
http-body = "0.4.4"
tracing = "0.1"

[dev-dependencies]
tower = { version = "0.4.4", features = ["util"] }
tokio = { version = "1.8.4", features = ["full"]}

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]
rustdoc-args = ["--cfg", "docsrs"]
# End of docs.rs metadata
