[package]
name = "pokemon-service-test"
version = "0.1.0"
edition = "2021"
publish = false
authors = ["Smithy-rs Server Team <smithy-rs-server@amazon.com>"]
description = "Run tests against the Python server implementation"

[dev-dependencies]
command-group = "1.0"
tokio = { version = "1.20.1", features = ["full"] }

# Local paths
aws-smithy-client  = { path = "../../../aws-smithy-client/", features = ["rustls"] }
aws-smithy-types  = { path = "../../../aws-smithy-types/" }
pokemon-service-client = { path = "../pokemon-service-client/" }
